-- Current Government of India LGD District directory, downloaded 2026-10-09.
-- Source: Ministry of Panchayati Raj LGD service, https://lgdirectory.gov.in/
-- Verified 36 India State/UTs and 784 current district rows, including their LGD district codes.
-- Existing district rows/IDs are preserved; uq_district_state_name makes reruns idempotent.
USE one_tap;

INSERT INTO districts (state_id,district_name) VALUES
  (29,'Nicobars'),
  (29,'North And Middle Andaman'),
  (29,'South Andamans'),
  (1,'Alluri Sitharama Raju'),
  (1,'Anakapalli'),
  (1,'Ananthapuramu'),
  (1,'Annamayya'),
  (1,'Bapatla'),
  (1,'Chittoor'),
  (1,'Dr. B.R. Ambedkar Konaseema'),
  (1,'East Godavari'),
  (1,'Eluru'),
  (1,'Guntur'),
  (1,'Kakinada'),
  (1,'Krishna'),
  (1,'Kurnool'),
  (1,'Markapuram'),
  (1,'Nandyal'),
  (1,'Ntr'),
  (1,'Palnadu'),
  (1,'Parvathipuram Manyam'),
  (1,'Polavaram'),
  (1,'Prakasam'),
  (1,'Srikakulam'),
  (1,'Sri Potti Sriramulu Nellore'),
  (1,'Sri Sathya Sai'),
  (1,'Tirupati'),
  (1,'Visakhapatnam'),
  (1,'Vizianagaram'),
  (1,'West Godavari'),
  (1,'Y.S.R. Kadapa'),
  (2,'Anjaw'),
  (2,'Bichom'),
  (2,'Changlang'),
  (2,'Dibang Valley'),
  (2,'East Kameng'),
  (2,'East Siang'),
  (2,'Kamle'),
  (2,'Keyi Panyor'),
  (2,'Kra Daadi'),
  (2,'Kurung Kumey'),
  (2,'Leparada'),
  (2,'Lohit'),
  (2,'Longding'),
  (2,'Lower Dibang Valley'),
  (2,'Lower Siang'),
  (2,'Lower Subansiri'),
  (2,'Namsai'),
  (2,'Pakke Kessang'),
  (2,'Papum Pare'),
  (2,'Shi Yomi'),
  (2,'Siang'),
  (2,'Tawang'),
  (2,'Tirap'),
  (2,'Upper Siang'),
  (2,'Upper Subansiri'),
  (2,'West Kameng'),
  (2,'West Siang'),
  (3,'Bajali'),
  (3,'Baksa'),
  (3,'Barpeta'),
  (3,'Biswanath'),
  (3,'Bongaigaon'),
  (3,'Cachar'),
  (3,'Charaideo'),
  (3,'Chirang'),
  (3,'Darrang'),
  (3,'Dhemaji'),
  (3,'Dhubri'),
  (3,'Dibrugarh'),
  (3,'Dima Hasao'),
  (3,'Goalpara'),
  (3,'Golaghat'),
  (3,'Hailakandi'),
  (3,'Hojai'),
  (3,'Jorhat'),
  (3,'Kamrup'),
  (3,'Kamrup Metro'),
  (3,'Karbi Anglong'),
  (3,'Kokrajhar'),
  (3,'Lakhimpur'),
  (3,'Majuli'),
  (3,'Marigaon'),
  (3,'Nagaon'),
  (3,'Nalbari'),
  (3,'Sivasagar'),
  (3,'Sonitpur'),
  (3,'South Salmara Mancachar'),
  (3,'Sribhumi'),
  (3,'Tamulpur'),
  (3,'Tinsukia'),
  (3,'Udalguri'),
  (3,'West Karbi Anglong'),
  (4,'Araria'),
  (4,'Arwal'),
  (4,'Aurangabad'),
  (4,'Banka'),
  (4,'Begusarai'),
  (4,'Bhagalpur'),
  (4,'Bhojpur')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);

INSERT INTO districts (state_id,district_name) VALUES
  (4,'Buxar'),
  (4,'Darbhanga'),
  (4,'Gaya'),
  (4,'Gopalganj'),
  (4,'Jamui'),
  (4,'Jehanabad'),
  (4,'Kaimur (Bhabua)'),
  (4,'Katihar'),
  (4,'Khagaria'),
  (4,'Kishanganj'),
  (4,'Lakhisarai'),
  (4,'Madhepura'),
  (4,'Madhubani'),
  (4,'Munger'),
  (4,'Muzaffarpur'),
  (4,'Nalanda'),
  (4,'Nawada'),
  (4,'Pashchim Champaran'),
  (4,'Patna'),
  (4,'Purbi Champaran'),
  (4,'Purnia'),
  (4,'Rohtas'),
  (4,'Saharsa'),
  (4,'Samastipur'),
  (4,'Saran'),
  (4,'Sheikhpura'),
  (4,'Sheohar'),
  (4,'Sitamarhi'),
  (4,'Siwan'),
  (4,'Supaul'),
  (4,'Vaishali'),
  (30,'Chandigarh'),
  (5,'Balod'),
  (5,'Balodabazar-Bhatapara'),
  (5,'Balrampur-Ramanujganj'),
  (5,'Bastar'),
  (5,'Bemetara'),
  (5,'Bijapur'),
  (5,'Bilaspur'),
  (5,'Dakshin Bastar Dantewada'),
  (5,'Dhamtari'),
  (5,'Durg'),
  (5,'Gariyaband'),
  (5,'Gaurela-Pendra-Marwahi'),
  (5,'Janjgir-Champa'),
  (5,'Jashpur'),
  (5,'Kabeerdham'),
  (5,'Khairagarh-Chhuikhadan-Gandai'),
  (5,'Kondagaon'),
  (5,'Korba'),
  (5,'Korea'),
  (5,'Mahasamund'),
  (5,'Manendragarh-Chirmiri-Bharatpur(M C B)'),
  (5,'Mohla-Manpur-Ambagarh Chouki'),
  (5,'Mungeli'),
  (5,'Narayanpur'),
  (5,'Raigarh'),
  (5,'Raipur'),
  (5,'Rajnandgaon'),
  (5,'Sakti'),
  (5,'Sarangarh-Bilaigarh'),
  (5,'Sukma'),
  (5,'Surajpur'),
  (5,'Surguja'),
  (5,'Uttar Bastar Kanker'),
  (32,'Central'),
  (32,'Central North'),
  (32,'East'),
  (32,'New Delhi'),
  (32,'North'),
  (32,'North East'),
  (32,'North West'),
  (32,'Old Delhi'),
  (32,'Outer North'),
  (32,'South'),
  (32,'South East'),
  (32,'South West'),
  (32,'West'),
  (6,'Kushavati'),
  (6,'North Goa'),
  (6,'South Goa'),
  (7,'Ahmedabad'),
  (7,'Amreli'),
  (7,'Anand'),
  (7,'Arvalli'),
  (7,'Banas Kantha'),
  (7,'Bharuch'),
  (7,'Bhavnagar'),
  (7,'Botad'),
  (7,'Chhotaudepur'),
  (7,'Dahod'),
  (7,'Dangs'),
  (7,'Devbhumi Dwarka'),
  (7,'Gandhinagar'),
  (7,'Gir Somnath'),
  (7,'Jamnagar'),
  (7,'Junagadh'),
  (7,'Kachchh'),
  (7,'Kheda'),
  (7,'Mahesana')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);

INSERT INTO districts (state_id,district_name) VALUES
  (7,'Mahisagar'),
  (7,'Morbi'),
  (7,'Narmada'),
  (7,'Navsari'),
  (7,'Panch Mahals'),
  (7,'Patan'),
  (7,'Porbandar'),
  (7,'Rajkot'),
  (7,'Sabar Kantha'),
  (7,'Surat'),
  (7,'Surendranagar'),
  (7,'Tapi'),
  (7,'Vadodara'),
  (7,'Valsad'),
  (7,'Vav-Tharad'),
  (8,'Ambala'),
  (8,'Bhiwani'),
  (8,'Charkhi Dadri'),
  (8,'Faridabad'),
  (8,'Fatehabad'),
  (8,'Gurugram'),
  (8,'Hansi'),
  (8,'Hisar'),
  (8,'Jhajjar'),
  (8,'Jind'),
  (8,'Kaithal'),
  (8,'Karnal'),
  (8,'Kurukshetra'),
  (8,'Mahendragarh'),
  (8,'Nuh'),
  (8,'Palwal'),
  (8,'Panchkula'),
  (8,'Panipat'),
  (8,'Rewari'),
  (8,'Rohtak'),
  (8,'Sirsa'),
  (8,'Sonipat'),
  (8,'Yamunanagar'),
  (9,'Bilaspur'),
  (9,'Chamba'),
  (9,'Hamirpur'),
  (9,'Kangra'),
  (9,'Kinnaur'),
  (9,'Kullu'),
  (9,'Lahaul And Spiti'),
  (9,'Mandi'),
  (9,'Shimla'),
  (9,'Sirmaur'),
  (9,'Solan'),
  (9,'Una'),
  (33,'Anantnag'),
  (33,'Bandipora'),
  (33,'Baramulla'),
  (33,'Budgam'),
  (33,'Doda'),
  (33,'Ganderbal'),
  (33,'Jammu'),
  (33,'Kathua'),
  (33,'Kishtwar'),
  (33,'Kulgam'),
  (33,'Kupwara'),
  (33,'Poonch'),
  (33,'Pulwama'),
  (33,'Rajouri'),
  (33,'Ramban'),
  (33,'Reasi'),
  (33,'Samba'),
  (33,'Shopian'),
  (33,'Srinagar'),
  (33,'Udhampur'),
  (10,'Bokaro'),
  (10,'Chatra'),
  (10,'Deoghar'),
  (10,'Dhanbad'),
  (10,'Dumka'),
  (10,'East Singhbum'),
  (10,'Garhwa'),
  (10,'Giridih'),
  (10,'Godda'),
  (10,'Gumla'),
  (10,'Hazaribagh'),
  (10,'Jamtara'),
  (10,'Khunti'),
  (10,'Koderma'),
  (10,'Latehar'),
  (10,'Lohardaga'),
  (10,'Pakur'),
  (10,'Palamu'),
  (10,'Ramgarh'),
  (10,'Ranchi'),
  (10,'Sahebganj'),
  (10,'Saraikela Kharsawan'),
  (10,'Simdega'),
  (10,'West Singhbhum'),
  (11,'Bagalkote'),
  (11,'Ballari'),
  (11,'Belagavi'),
  (11,'Bengaluru Rural'),
  (11,'Bengaluru South'),
  (11,'Bengaluru Urban')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);

INSERT INTO districts (state_id,district_name) VALUES
  (11,'Bidar'),
  (11,'Chamarajanagar'),
  (11,'Chikkaballapura'),
  (11,'Chikkamagaluru'),
  (11,'Chitradurga'),
  (11,'Dakshina Kannada'),
  (11,'Davanagere'),
  (11,'Dharwad'),
  (11,'Gadag'),
  (11,'Hassan'),
  (11,'Haveri'),
  (11,'Kalaburagi'),
  (11,'Kodagu'),
  (11,'Kolar'),
  (11,'Koppal'),
  (11,'Mandya'),
  (11,'Mysuru'),
  (11,'Raichur'),
  (11,'Shivamogga'),
  (11,'Tumakuru'),
  (11,'Udupi'),
  (11,'Uttara Kannada'),
  (11,'Vijayanagara'),
  (11,'Vijayapura'),
  (11,'Yadgir'),
  (12,'Alappuzha'),
  (12,'Ernakulam'),
  (12,'Idukki'),
  (12,'Kannur'),
  (12,'Kasaragod'),
  (12,'Kollam'),
  (12,'Kottayam'),
  (12,'Kozhikode'),
  (12,'Malappuram'),
  (12,'Palakkad'),
  (12,'Pathanamthitta'),
  (12,'Thiruvananthapuram'),
  (12,'Thrissur'),
  (12,'Wayanad'),
  (34,'Kargil'),
  (34,'Leh Ladakh'),
  (35,'Lakshadweep District'),
  (13,'Agar-Malwa'),
  (13,'Alirajpur'),
  (13,'Anuppur'),
  (13,'Ashoknagar'),
  (13,'Balaghat'),
  (13,'Barwani'),
  (13,'Betul'),
  (13,'Bhind'),
  (13,'Bhopal'),
  (13,'Burhanpur'),
  (13,'Chhatarpur'),
  (13,'Chhindwara'),
  (13,'Damoh'),
  (13,'Datia'),
  (13,'Dewas'),
  (13,'Dhar'),
  (13,'Dindori'),
  (13,'Guna'),
  (13,'Gwalior'),
  (13,'Harda'),
  (13,'Indore'),
  (13,'Jabalpur'),
  (13,'Jhabua'),
  (13,'Katni'),
  (13,'Khandwa (East Nimar)'),
  (13,'Khargone (West Nimar)'),
  (13,'Maihar'),
  (13,'Mandla'),
  (13,'Mandsaur'),
  (13,'MAUGANJ'),
  (13,'Morena'),
  (13,'Narmadapuram'),
  (13,'Narsimhapur'),
  (13,'Neemuch'),
  (13,'Niwari'),
  (13,'Pandhurna'),
  (13,'Panna'),
  (13,'Raisen'),
  (13,'Rajgarh'),
  (13,'Ratlam'),
  (13,'Rewa'),
  (13,'Sagar'),
  (13,'Satna'),
  (13,'Sehore'),
  (13,'Seoni'),
  (13,'Shahdol'),
  (13,'Shajapur'),
  (13,'Sheopur'),
  (13,'Shivpuri'),
  (13,'Sidhi'),
  (13,'Singrauli'),
  (13,'Tikamgarh'),
  (13,'Ujjain'),
  (13,'Umaria'),
  (13,'Vidisha'),
  (14,'Ahilyanagar'),
  (14,'Akola'),
  (14,'Amravati')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);

INSERT INTO districts (state_id,district_name) VALUES
  (14,'Beed'),
  (14,'Bhandara'),
  (14,'Buldhana'),
  (14,'Chandrapur'),
  (14,'Chhatrapati Sambhajinagar'),
  (14,'Dharashiv'),
  (14,'Dhule'),
  (14,'Gadchiroli'),
  (14,'Gondia'),
  (14,'Hingoli'),
  (14,'Jalgaon'),
  (14,'Jalna'),
  (14,'Kolhapur'),
  (14,'Latur'),
  (14,'Mumbai'),
  (14,'Mumbai Suburban'),
  (14,'Nagpur'),
  (14,'Nanded'),
  (14,'Nandurbar'),
  (14,'Nashik'),
  (14,'Palghar'),
  (14,'Parbhani'),
  (14,'Pune'),
  (14,'Raigad'),
  (14,'Ratnagiri'),
  (14,'Sangli'),
  (14,'Satara'),
  (14,'Sindhudurg'),
  (14,'Solapur'),
  (14,'Thane'),
  (14,'Wardha'),
  (14,'Washim'),
  (14,'Yavatmal'),
  (15,'Bishnupur'),
  (15,'Chandel'),
  (15,'Churachandpur'),
  (15,'Imphal East'),
  (15,'Imphal West'),
  (15,'Jiribam'),
  (15,'Kakching'),
  (15,'Kamjong'),
  (15,'Kangpokpi'),
  (15,'Noney'),
  (15,'Pherzawl'),
  (15,'Senapati'),
  (15,'Tamenglong'),
  (15,'Tengnoupal'),
  (15,'Thoubal'),
  (15,'Ukhrul'),
  (16,'Eastern West Khasi Hills'),
  (16,'East Garo Hills'),
  (16,'East Jaintia Hills'),
  (16,'East Khasi Hills'),
  (16,'North Garo Hills'),
  (16,'Ri Bhoi'),
  (16,'South Garo Hills'),
  (16,'South West Garo Hills'),
  (16,'South West Khasi Hills'),
  (16,'West Garo Hills'),
  (16,'West Jaintia Hills'),
  (16,'West Khasi Hills'),
  (17,'Aizawl'),
  (17,'Champhai'),
  (17,'Hnahthial'),
  (17,'Khawzawl'),
  (17,'Kolasib'),
  (17,'Lawngtlai'),
  (17,'Lunglei'),
  (17,'Mamit'),
  (17,'Saitual'),
  (17,'Serchhip'),
  (17,'Siaha'),
  (18,'Chumoukedima'),
  (18,'Dimapur'),
  (18,'Kiphire'),
  (18,'Kohima'),
  (18,'Longleng'),
  (18,'Meluri'),
  (18,'Mokokchung'),
  (18,'Mon'),
  (18,'Niuland'),
  (18,'Noklak'),
  (18,'Peren'),
  (18,'Phek'),
  (18,'Shamator'),
  (18,'Tseminyu'),
  (18,'Tuensang'),
  (18,'Wokha'),
  (18,'Zunheboto'),
  (19,'Angul'),
  (19,'Balangir'),
  (19,'Balasore'),
  (19,'Bargarh'),
  (19,'Bhadrak'),
  (19,'Boudh'),
  (19,'Cuttack'),
  (19,'Deogarh'),
  (19,'Dhenkanal'),
  (19,'Gajapati'),
  (19,'Ganjam')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);

INSERT INTO districts (state_id,district_name) VALUES
  (19,'Jagatsinghapur'),
  (19,'Jajpur'),
  (19,'Jharsuguda'),
  (19,'Kalahandi'),
  (19,'Kandhamal'),
  (19,'Kendrapara'),
  (19,'Keonjhar'),
  (19,'Khordha'),
  (19,'Koraput'),
  (19,'Malkangiri'),
  (19,'Mayurbhanj'),
  (19,'Nabarangpur'),
  (19,'Nayagarh'),
  (19,'Nuapada'),
  (19,'Puri'),
  (19,'Rayagada'),
  (19,'Sambalpur'),
  (19,'Sonepur'),
  (19,'Sundargarh'),
  (36,'Karaikal'),
  (36,'Puducherry'),
  (20,'Amritsar'),
  (20,'Barnala'),
  (20,'Bathinda'),
  (20,'Faridkot'),
  (20,'Fatehgarh Sahib'),
  (20,'Fazilka'),
  (20,'Ferozepur'),
  (20,'Gurdaspur'),
  (20,'Hoshiarpur'),
  (20,'Jalandhar'),
  (20,'Kapurthala'),
  (20,'Ludhiana'),
  (20,'Malerkotla'),
  (20,'Mansa'),
  (20,'Moga'),
  (20,'Pathankot'),
  (20,'Patiala'),
  (20,'Rupnagar'),
  (20,'Sangrur'),
  (20,'S.A.S Nagar'),
  (20,'Shahid Bhagat Singh Nagar'),
  (20,'Sri Muktsar Sahib'),
  (20,'Tarn Taran'),
  (21,'Ajmer'),
  (21,'Alwar'),
  (21,'Balotra'),
  (21,'Banswara'),
  (21,'Baran'),
  (21,'Barmer'),
  (21,'Beawar'),
  (21,'Bharatpur'),
  (21,'Bhilwara'),
  (21,'Bikaner'),
  (21,'Bundi'),
  (21,'Chittorgarh'),
  (21,'Churu'),
  (21,'Dausa'),
  (21,'Deeg'),
  (21,'Dholpur'),
  (21,'Didwana-Kuchaman'),
  (21,'Dungarpur'),
  (21,'Ganganagar'),
  (21,'Hanumangarh'),
  (21,'Jaipur'),
  (21,'Jaisalmer'),
  (21,'Jalore'),
  (21,'Jhalawar'),
  (21,'Jhunjhunu'),
  (21,'Jodhpur'),
  (21,'Karauli'),
  (21,'Khairthal-Tijara'),
  (21,'Kota'),
  (21,'Kotputli-Behror'),
  (21,'Nagaur'),
  (21,'Pali'),
  (21,'Phalodi'),
  (21,'Pratapgarh'),
  (21,'Rajsamand'),
  (21,'Salumbar'),
  (21,'Sawai Madhopur'),
  (21,'Sikar'),
  (21,'Sirohi'),
  (21,'Tonk'),
  (21,'Udaipur'),
  (22,'Gangtok'),
  (22,'Gyalshing'),
  (22,'Mangan'),
  (22,'Namchi'),
  (22,'Pakyong'),
  (22,'Soreng'),
  (23,'Ariyalur'),
  (23,'Chengalpattu'),
  (23,'Chennai'),
  (23,'Coimbatore'),
  (23,'Cuddalore'),
  (23,'Dharmapuri'),
  (23,'Dindigul'),
  (23,'Erode'),
  (23,'Kallakurichi')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);

INSERT INTO districts (state_id,district_name) VALUES
  (23,'Kancheepuram'),
  (23,'Kanniyakumari'),
  (23,'Karur'),
  (23,'Krishnagiri'),
  (23,'Madurai'),
  (23,'Mayiladuthurai'),
  (23,'Nagapattinam'),
  (23,'Namakkal'),
  (23,'Perambalur'),
  (23,'Pudukkottai'),
  (23,'Ramanathapuram'),
  (23,'Ranipet'),
  (23,'Salem'),
  (23,'Sivaganga'),
  (23,'Tenkasi'),
  (23,'Thanjavur'),
  (23,'Theni'),
  (23,'The Nilgiris'),
  (23,'Thiruvallur'),
  (23,'Thiruvarur'),
  (23,'Thoothukkudi'),
  (23,'Tiruchirappalli'),
  (23,'Tirunelveli'),
  (23,'Tirupathur'),
  (23,'Tiruppur'),
  (23,'Tiruvannamalai'),
  (23,'Vellore'),
  (23,'Viluppuram'),
  (23,'Virudhunagar'),
  (24,'Adilabad'),
  (24,'Bhadradri Kothagudem'),
  (24,'Hanumakonda'),
  (24,'Hyderabad'),
  (24,'Jagitial'),
  (24,'Jangoan'),
  (24,'Jayashankar Bhupalapally'),
  (24,'Jogulamba Gadwal'),
  (24,'Kamareddy'),
  (24,'Karimnagar'),
  (24,'Khammam'),
  (24,'Kumuram Bheem Asifabad'),
  (24,'Mahabubabad'),
  (24,'Mahabubnagar'),
  (24,'Mancherial'),
  (24,'Medak'),
  (24,'Medchal Malkajgiri'),
  (24,'Mulugu'),
  (24,'Nagarkurnool'),
  (24,'Nalgonda'),
  (24,'Narayanpet'),
  (24,'Nirmal'),
  (24,'Nizamabad'),
  (24,'Peddapalli'),
  (24,'Rajanna Sircilla'),
  (24,'Ranga Reddy'),
  (24,'Sangareddy'),
  (24,'Siddipet'),
  (24,'Suryapet'),
  (24,'Vikarabad'),
  (24,'Wanaparthy'),
  (24,'Warangal'),
  (24,'Yadadri Bhuvanagiri'),
  (31,'Dadra And Nagar Haveli'),
  (31,'Daman'),
  (31,'Diu'),
  (25,'Dhalai'),
  (25,'Gomati'),
  (25,'Khowai'),
  (25,'North Tripura'),
  (25,'Sepahijala'),
  (25,'South Tripura'),
  (25,'Unakoti'),
  (25,'West Tripura'),
  (27,'Almora'),
  (27,'Bageshwar'),
  (27,'Chamoli'),
  (27,'Champawat'),
  (27,'Dehradun'),
  (27,'Haridwar'),
  (27,'Nainital'),
  (27,'Pauri Garhwal'),
  (27,'Pithoragarh'),
  (27,'Rudraprayag'),
  (27,'Tehri Garhwal'),
  (27,'Udham Singh Nagar'),
  (27,'Uttarkashi'),
  (26,'Agra'),
  (26,'Aligarh'),
  (26,'Ambedkar Nagar'),
  (26,'Amethi'),
  (26,'Amroha'),
  (26,'Auraiya'),
  (26,'Ayodhya'),
  (26,'Azamgarh'),
  (26,'Baghpat'),
  (26,'Bahraich'),
  (26,'Ballia'),
  (26,'Balrampur'),
  (26,'Banda'),
  (26,'Bara Banki')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);

INSERT INTO districts (state_id,district_name) VALUES
  (26,'Bareilly'),
  (26,'Basti'),
  (26,'Bhadohi'),
  (26,'Bijnor'),
  (26,'Budaun'),
  (26,'Bulandshahr'),
  (26,'Chandauli'),
  (26,'Chitrakoot'),
  (26,'Deoria'),
  (26,'Etah'),
  (26,'Etawah'),
  (26,'Farrukhabad'),
  (26,'Fatehpur'),
  (26,'Firozabad'),
  (26,'Gautam Buddha Nagar'),
  (26,'Ghaziabad'),
  (26,'Ghazipur'),
  (26,'Gonda'),
  (26,'Gorakhpur'),
  (26,'Hamirpur'),
  (26,'Hapur'),
  (26,'Hardoi'),
  (26,'Hathras'),
  (26,'Jalaun'),
  (26,'Jaunpur'),
  (26,'Jhansi'),
  (26,'Kannauj'),
  (26,'Kanpur Dehat'),
  (26,'Kanpur Nagar'),
  (26,'Kasganj'),
  (26,'Kaushambi'),
  (26,'Kheri'),
  (26,'Kushinagar'),
  (26,'Lalitpur'),
  (26,'Lucknow'),
  (26,'Mahoba'),
  (26,'Mahrajganj'),
  (26,'Mainpuri'),
  (26,'Mathura'),
  (26,'Mau'),
  (26,'Meerut'),
  (26,'Mirzapur'),
  (26,'Moradabad'),
  (26,'Muzaffarnagar'),
  (26,'Pilibhit'),
  (26,'Pratapgarh'),
  (26,'Prayagraj'),
  (26,'Rae Bareli'),
  (26,'Rampur'),
  (26,'Saharanpur'),
  (26,'Sambhal'),
  (26,'Sant Kabir Nagar'),
  (26,'Shahjahanpur'),
  (26,'Shamli'),
  (26,'Shrawasti'),
  (26,'Siddharthnagar'),
  (26,'Sitapur'),
  (26,'Sonbhadra'),
  (26,'Sultanpur'),
  (26,'Unnao'),
  (26,'Varanasi'),
  (28,'Alipurduar'),
  (28,'Bankura'),
  (28,'Birbhum'),
  (28,'Cooch Behar'),
  (28,'Dakshin Dinajpur'),
  (28,'Darjeeling'),
  (28,'Hooghly'),
  (28,'Howrah'),
  (28,'Jalpaiguri'),
  (28,'Jhargram'),
  (28,'Kalimpong'),
  (28,'Kolkata'),
  (28,'Malda'),
  (28,'Murshidabad'),
  (28,'Nadia'),
  (28,'North 24 Parganas'),
  (28,'Paschim Bardhaman'),
  (28,'Paschim Medinipur'),
  (28,'Purba Bardhaman'),
  (28,'Purba Medinipur'),
  (28,'Purulia'),
  (28,'South 24 Parganas'),
  (28,'Uttar Dinajpur')
ON DUPLICATE KEY UPDATE district_name=VALUES(district_name);
