(() => {
  'use strict';
  const pageHost = location.hostname || 'localhost';
  const isLocalDevServer = ['5500', '5501', '5173', '3000'].includes(location.port) || location.protocol === 'file:';
  const defaultApi = isLocalDevServer
    ? `http://${pageHost}:8080/one-tap-backend-1.0`
    : `${location.origin}/one-tap-backend-1.0`;
  const API = (localStorage.getItem('oneTapApi') || defaultApi).replace(/\/$/, '');
  const app = document.querySelector('#app');
  let user = null, profile = null, contacts = [], geo = null, timer = null, audio = null, audioContext = null;
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast = m => { const el=document.querySelector('#toast'); el.textContent=m; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),3500); };
  const formData = data => new URLSearchParams(Object.entries(data).filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=>[k,String(v)]));
  async function request(path, data, method='POST') {
    const opts={method,credentials:'include',headers:{Accept:'application/json'}};
    if(data) { opts.headers['Content-Type']='application/x-www-form-urlencoded;charset=UTF-8'; opts.body=formData(data); }
    let res; try { res=await fetch(`${API}/${path}`,opts); } catch { throw Error(`Cannot reach backend at ${API}. Check that Tomcat is running, the backend is deployed, and the frontend origin is allowed by CORS.`); }
    let body; try { body=await res.json(); } catch { body={}; }
    if(!res.ok) throw Error(body.message || `Request failed (${res.status}).`);
    return body;
  }
  function shell(content, back='') { app.innerHTML=`<div class="page"><header class="top"><button class="back ${back?'':'hidden'}" data-back>←</button><a class="brand" href="#" aria-label="One Tap home"><span class="brand-mark">1</span> ONE TAP</a></header>${content}</div>`; app.querySelector('[data-back]')?.addEventListener('click',()=>navigate(back)); }
  function navigate(page) { location.hash=page; render(); }
  function message(id,text){const e=document.getElementById(id);if(e)e.textContent=text;}
  function welcome(){shell(`<section class="welcome"><div class="logo">1</div><h1>ONE TAP</h1><div class="actions"><button class="primary" data-page="login">Login</button><button class="secondary" data-page="register">Register</button></div></section>`);}
  function authPage(mode){const reg=mode==='register';shell(`<section class="panel narrow"><p class="eyebrow">${reg?'STEP 1: USER IDENTIFICATION':'WELCOME BACK'}</p><h1>${reg?'Create your account':'Login'}</h1><form id="authForm" novalidate>${reg?'<label>Full name<input name="fullName" autocomplete="name" required minlength="2"></label>':''}<label>Email address<input name="email" type="email" autocomplete="email" required></label>${reg?'<label>Phone number<input name="phoneNumber" type="tel" autocomplete="tel" required pattern="[+0-9 ()-]{8,20}"></label>':''}<label>Password<div class="password"><input name="password" type="password" autocomplete="${reg?'new-password':'current-password'}" required minlength="8"><button type="button" data-eye aria-label="Show password">Show</button></div></label>${reg?'<label>Confirm password<input name="confirmPassword" type="password" autocomplete="new-password" required></label>':''}<p class="error" id="authError" role="alert"></p><button class="primary" type="submit">${reg?'Create account':'Login'}</button></form><button class="text-button" data-page="${reg?'login':'register'}">${reg?'Already have an account? Login':'Register a new account'}</button></section>`, 'welcome');
    document.querySelector('[data-eye]').onclick=e=>{const input=e.currentTarget.previousElementSibling;input.type=input.type==='password'?'text':'password';e.currentTarget.textContent=input.type==='password'?'Show':'Hide';};
    document.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const error=document.querySelector('#authError');error.textContent='';if(!e.currentTarget.reportValidity())return;if(reg&&(f.password.length<10||!/[A-Za-z]/.test(f.password)||!/[0-9]/.test(f.password))){error.textContent='Use at least 10 characters, including a letter and a number.';return;}if(reg&&f.password!==f.confirmPassword){error.textContent='Passwords do not match.';return;}const btn=e.currentTarget.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Please wait…';try{if(reg){const result=await request('register',{fullName:f.fullName,email:f.email,phoneNumber:f.phoneNumber,password:f.password});user=result.user;toast('Account created. Complete your profile.');navigate('profile');}else{const result=await request('login',{email:f.email,password:f.password});user=result.user;await routeAfterLogin();}}catch(err){error.textContent=err.message;}finally{btn.disabled=false;btn.textContent=reg?'Create account':'Login';}};
  }
  async function routeAfterLogin(){try{profile=await request('profile',null,'GET');const c=await request('trusted-contacts',null,'GET');contacts=c.contacts||[];navigate(!profile.profileComplete?'profile':contacts.length<3?'contacts':'sos');}catch(e){toast(e.message);navigate('login');}}
  async function profilePage(){let locations;try{locations=await request('location-data',null,'GET');}catch(e){locations={countries:[],states:[],districts:[]};toast(e.message);}const countries=locations.countries||[],states=locations.states||[],districts=locations.districts||[];const countryOptions=countries.map(x=>`<option value="${x.countryId}">${esc(x.countryName)}</option>`).join('');const stateOptions=()=>states.filter(x=>String(x.countryId)===String(document.querySelector('[name=countryId]')?.value||'')).map(x=>`<option value="${x.stateId}">${esc(x.stateName)}</option>`).join('');const districtOptions=()=>districts.filter(x=>String(x.stateId)===String(document.querySelector('[name=stateId]')?.value||'')).map(x=>`<option value="${esc(x.districtName)}">${esc(x.districtName)}</option>`).join('');
    shell(`<section class="panel"><p class="eyebrow">STEP 2: PROFILE COMPLETION</p><h1>Your profile</h1><form id="profileForm" class="form-grid"><label>Full name<input name="fullName" required value="${esc(profile?.fullName||user?.fullName)}"></label><label>Email address<input name="email" type="email" required value="${esc(profile?.email||user?.email)}"></label><label>Phone number<input name="phoneNumber" type="tel" required value="${esc(profile?.phoneNumber||user?.phoneNumber)}"></label><label>Country<select name="countryId" required>${countryOptions}</select></label><label>State / Union Territory<select name="stateId" required><option value="">Select state</option></select></label><label>District<select name="district" required><option value="">${districts.length?'Select district':'No district data loaded'}</option></select></label><label>Local place / town<input name="locality" required value="${esc(profile?.locality||'')}"></label><label>Street address<input name="address" required value="${esc(profile?.address||'')}"></label><fieldset class="location"><legend>GPS location (device detected)</legend><button type="button" class="secondary" id="detectGps">Detect GPS Location</button><p id="gpsStatus" class="muted">${profile?.latitude!=null?`Saved location: ${esc(profile.latitude)}, ${esc(profile.longitude)} ±${esc(profile.accuracy)} m`:'Not detected'}</p><input type="hidden" name="latitude" value="${esc(profile?.latitude??'')}"><input type="hidden" name="longitude" value="${esc(profile?.longitude??'')}"><input type="hidden" name="accuracy" value="${esc(profile?.accuracy??'')}"></fieldset><p class="error full" id="profileError" role="alert"></p><button class="primary full" type="submit">Save Profile</button></form></section>`, 'welcome');
    const country=document.querySelector('[name=countryId]'),state=document.querySelector('[name=stateId]'),district=document.querySelector('[name=district]');if(profile?.countryId)country.value=profile.countryId;const fillStates=(keep)=>{state.innerHTML='<option value="">Select state</option>'+stateOptions();if(keep)state.value=profile?.stateId||'';};const fillDistricts=(keep)=>{district.innerHTML=`<option value="">${districts.length?'Select district':'No district data loaded'}</option>`+districtOptions();if(keep)district.value=profile?.district||'';};fillStates(true);fillDistricts(true);country.onchange=()=>{state.value='';district.value='';fillStates(false);fillDistricts(false);};state.onchange=()=>fillDistricts(false);
    document.querySelector('#detectGps').onclick=()=>{const status=document.querySelector('#gpsStatus');if(!navigator.geolocation){status.textContent='Location is unavailable in this browser.';status.className='error';return;}status.textContent='Detecting location…';status.className='muted';navigator.geolocation.getCurrentPosition(pos=>{geo=pos.coords;for(const [n,v] of [['latitude',geo.latitude],['longitude',geo.longitude],['accuracy',geo.accuracy]])document.querySelector(`[name=${n}]`).value=v;status.textContent=`Detected: ${geo.latitude.toFixed(6)}, ${geo.longitude.toFixed(6)} ±${Math.round(geo.accuracy)} m`;status.className='success';},err=>{status.textContent=err.code===1?'Location permission denied.':'Location could not be detected. Retry when ready.';status.className='error';},{enableHighAccuracy:true,timeout:15000,maximumAge:0});};
    document.querySelector('#profileForm').onsubmit=async e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const d=Object.fromEntries(new FormData(e.currentTarget));const b=e.currentTarget.querySelector('button[type=submit]');b.disabled=true;try{profile=await request('profile',d);toast('Profile saved.');navigate('contacts');}catch(err){message('profileError',err.message);}finally{b.disabled=false;}};
  }
  function contactPage(){const rows=contacts.length?contacts.map((c,i)=>`<div class="contact-row"><label>Name<input data-c="name" data-i="${i}" value="${esc(c.contactName)}" required></label><label>Phone<input data-c="phone" data-i="${i}" value="${esc(c.phoneNumber)}" required pattern="[+0-9 ()-]{8,20}"></label><label>Relationship<input data-c="relationship" data-i="${i}" value="${esc(c.relationship)}" required></label><button class="remove" data-remove="${i}" type="button" aria-label="Remove contact">Remove</button></div>`).join(''):'<p class="muted">No emergency contacts have been saved.</p>';
    shell(`<section class="panel"><p class="eyebrow">STEP 3: EMERGENCY CONTACT SETUP</p><h1>Trusted contacts</h1><div id="contactList">${rows}</div><div class="actions"><button class="secondary" id="addContact">Add contact</button><button class="primary" id="saveContacts">Save contacts</button></div><p class="muted">Add at least three trusted contacts to finish setup.</p><p class="error" id="contactError" role="alert"></p></section>`, 'profile');
    document.querySelector('#addContact').onclick=()=>{contacts.push({contactName:'',phoneNumber:'',relationship:''});contactPage();};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{contacts.splice(Number(b.dataset.remove),1);contactPage();});
    document.querySelector('#saveContacts').onclick=async()=>{const error=document.querySelector('#contactError');error.textContent='';contacts=contacts.map((c,i)=>({contactName:document.querySelector(`[data-i="${i}"][data-c="name"]`)?.value.trim()||'',phoneNumber:document.querySelector(`[data-i="${i}"][data-c="phone"]`)?.value.trim()||'',relationship:document.querySelector(`[data-i="${i}"][data-c="relationship"]`)?.value.trim()||''}));if(contacts.length<3||contacts.some(c=>!c.contactName||!/^\+?[0-9 ()-]{8,20}$/.test(c.phoneNumber)||!c.relationship)){error.textContent='Enter at least three valid contacts with name, phone, and relationship.';return;}const b=document.querySelector('#saveContacts');b.disabled=true;try{await request('trusted-contacts',{contacts:JSON.stringify(contacts)});toast('Contacts saved.');navigate('sos');}catch(e){error.textContent=e.message;}finally{b.disabled=false;}};
  }
  function tabbar(active){return `<nav class="tabs"><button data-tab="sos" class="${active==='sos'?'active':''}">SOS</button><button data-tab="contacts" class="${active==='contacts'?'active':''}">Contacts</button><button data-tab="account" class="${active==='account'?'active':''}">Account</button></nav>`;}
  async function loadShared(){if(!user){await request('session',null,'GET').then(r=>user=r.user).catch(()=>{});}if(user){profile=await request('profile',null,'GET');const r=await request('trusted-contacts',null,'GET');contacts=r.contacts||[];}}
  async function dashboard(which){try{await loadShared();}catch(e){toast(e.message);navigate('login');return;}if(which==='contacts'){contactScreen();return;}if(which==='account'){accountScreen();return;}sosScreen();}
  function contactScreen(){const rows=contacts.map(c=>`<article class="contact-card"><b>${esc(c.contactName)}</b><span>${esc(c.relationship)}</span><a href="tel:${encodeURIComponent(c.phoneNumber)}">${esc(c.phoneNumber)}</a></article>`).join('');shell(`<div class="dashboard"><h1>One Tap — SOS Emergency Call</h1><section class="panel"><h2>Emergency contacts</h2>${rows||'<p class="muted">No contacts saved yet.</p>'}<button class="secondary" data-edit-contacts>Edit contacts</button></section>${tabbar('contacts')}</div>`);tabs();document.querySelector('[data-edit-contacts]').onclick=()=>navigate('contacts-setup');}
  function accountScreen(){shell(`<div class="dashboard"><h1>One Tap — SOS Emergency Call</h1><section class="panel"><h2>Account</h2><dl>${[['Full name',profile?.fullName],['Email',profile?.email],['Phone',profile?.phoneNumber],['Country',profile?.countryName],['State / UT',profile?.stateName],['District',profile?.district],['Place',profile?.locality],['Address',profile?.address],['GPS latitude',profile?.latitude],['GPS longitude',profile?.longitude],['Accuracy',profile?.accuracy==null?'':`${profile.accuracy} m`]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v||'—')}</dd></div>`).join('')}</dl><button class="secondary" data-edit-profile>Edit profile</button><button class="text-button" id="logout">Log out</button></section>${tabbar('account')}</div>`);tabs();document.querySelector('[data-edit-profile]').onclick=()=>navigate('profile');document.querySelector('#logout').onclick=async()=>{try{await request('session',{});}catch{}user=null;profile=null;contacts=[];navigate('welcome');};}
  function tabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.tab));}
  function sosScreen(){shell(`<div class="dashboard"><h1>One Tap — SOS Emergency Call</h1><section class="sos-panel"><p class="eyebrow">EMERGENCY ALERT</p><button class="sos-button" id="sos" aria-describedby="sosStatus">SOS</button><p id="sosStatus" role="status">Press SOS to start the 3-second safety window.</p><button class="secondary hidden" id="cancel">Cancel alert</button><p id="dispatchStatus" role="status"></p></section><section class="panel"><h2>Phone Safety Utilities</h2><div class="utility-grid"><button class="secondary" id="strobe">SOS Strobe Light</button><button class="secondary" id="whistle">Safety Whistle</button><button class="secondary" id="whatsapp">Share via WhatsApp</button><button class="secondary" id="sms">Send SMS Alert</button><button class="secondary" id="siren">Start siren</button><span id="battery" class="muted">Battery status unavailable</span></div></section><section class="panel"><h2>Official India helplines</h2><div class="helplines"><a href="tel:112">Integrated emergency response — 112</a><a href="tel:102">National ambulance service — 102</a><a href="tel:100">Police — 100</a><a href="tel:101">Fire — 101</a><a href="tel:181">Women’s helpline — 181</a></div></section>${tabbar('sos')}</div>`);tabs();wireSOS();}
  async function wireSOS(){const status=document.querySelector('#sosStatus'),cancel=document.querySelector('#cancel'),button=document.querySelector('#sos');let cancelled=false;button.onclick=()=>{if(timer)return;cancelled=false;let n=3;status.textContent=`Alert will be dispatched in ${n} seconds.`;cancel.classList.remove('hidden');if(navigator.vibrate)navigator.vibrate([150,80,150]);timer=setInterval(()=>{n--;if(n>0){status.textContent=`Alert will be dispatched in ${n} seconds.`;return;}clearInterval(timer);timer=null;cancel.classList.add('hidden');if(!cancelled)dispatchSOS();},1000);};cancel.onclick=()=>{cancelled=true;clearInterval(timer);timer=null;cancel.classList.add('hidden');status.textContent='Alert cancelled. No dispatch was requested.';};
    async function dispatchSOS(){status.textContent='Submitting alert…';let coords=geo||null;if(!coords&&navigator.geolocation)try{coords=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve(p.coords),reject,{enableHighAccuracy:true,timeout:10000,maximumAge:60000}));}catch{}try{const result=await request('sos',{latitude:coords?.latitude,longitude:coords?.longitude,accuracy:coords?.accuracy});status.textContent=result.message||'SOS request processed.';document.querySelector('#dispatchStatus').textContent=(result.calls||[]).map(c=>`${c.contactName}: ${c.status}`).join(' · ')||'Dispatch status unavailable.';}catch(e){status.textContent=`Alert dispatch failed: ${e.message}`;}}
    let strobeOn=false;document.querySelector('#strobe').onclick=()=>{strobeOn=!strobeOn;document.body.classList.toggle('strobe',strobeOn);document.querySelector('#strobe').textContent=`SOS Strobe Light: ${strobeOn?'ON':'OFF'} (screen)`;};document.querySelector('#whistle').onclick=()=>{if(audio){audio.stop();audio=null;document.querySelector('#whistle').textContent='Safety Whistle';return;}try{const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error();audioContext=new C();audio=audioContext.createOscillator();const gain=audioContext.createGain();audio.frequency.value=3000;gain.gain.value=.12;audio.connect(gain);gain.connect(audioContext.destination);audio.start();document.querySelector('#whistle').textContent='Stop whistle';}catch{toast('Audio is unavailable.');}};
    document.querySelector('#whatsapp').onclick=()=>{const text=makeAlertText();if(confirm('Open WhatsApp to choose a recipient and review the alert?'))window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener');};document.querySelector('#sms').onclick=()=>{location.href=`sms:?body=${encodeURIComponent(makeAlertText())}`;document.querySelector('#dispatchStatus').textContent='SMS composer opened; message is not yet sent.';};let sirenOn=false;document.querySelector('#siren').onclick=()=>{if(sirenOn){audio?.stop();audio=null;sirenOn=false;document.querySelector('#siren').textContent='Start siren';return;}try{const C=window.AudioContext||window.webkitAudioContext;audioContext=new C();audio=audioContext.createOscillator();const g=audioContext.createGain();audio.frequency.value=850;g.gain.value=.08;audio.connect(g);g.connect(audioContext.destination);audio.start();sirenOn=true;document.querySelector('#siren').textContent='Stop siren';}catch{toast('Audio is unavailable.');}};
    if(navigator.getBattery)navigator.getBattery().then(b=>{const show=()=>document.querySelector('#battery').textContent=`Battery ${Math.round(b.level*100)}%${b.charging?' · Charging':''}`;show();b.addEventListener('levelchange',show);b.addEventListener('chargingchange',show);}).catch(()=>{});
  }
  function makeAlertText(){const c=geo||((profile?.latitude!=null)?{latitude:profile.latitude,longitude:profile.longitude}:null);return `Emergency alert from One Tap.${c?` Location: https://maps.google.com/?q=${c.latitude},${c.longitude}`:''}`;}
  async function render(){const page=location.hash.slice(1)||'welcome';if(!user&&['sos','contacts','account'].includes(page)){try{const r=await request('session',null,'GET');user=r.user;}catch{navigate('welcome');return;}}switch(page){case'login':authPage('login');break;case'register':authPage('register');break;case'profile':await profilePage();break;case'contacts-setup':try{await loadShared();contactPage();}catch(e){toast(e.message);navigate('login');}break;case'contacts':case'account':case'sos':await dashboard(page);break;case'welcome':default:welcome();}
    document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
  }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)navigate(b.dataset.page);});window.addEventListener('hashchange',render);render();
})();
